---
- name: Uninstalling firewall using host scope variables
  hosts: webserver
  tasks:
   - name: Uninstall firewall
     apt:
      name: "{{f}}"
      state: "{{g}}"
      update_cache: "{{h}}"

